<header>
</header>

<main>
<br><bR>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-6">
        <img src="http://jhaegman.com/stool.svg" id="imgMain">
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-2 autresPhotos">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <img src="http://via.placeholder.com/150x150" style="max-width:100%"><br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <img src="http://via.placeholder.com/150x150" style="max-width:100%"><br>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <img src="http://via.placeholder.com/150x150" style="max-width:100%"><br>
            </div>
        </div>
    </div>
    <div class="DescProduit col-lg-4 col-md-4 col-sm-4 col-12" style="height:400px">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <span class="produitDescTitre" style="font-size:1.5em"><?= $this->escapeHtml($product->_name)?></span>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <p class="produitDescParagraphe"><?= $this->escapeHtml($product->_description)?></p><br><br>
            </div>
            <div>
                <span class="produitDescPrix"><?=$this->escapeHtml($product->_price)?>$CAN</span><br><a class="btn btn-outlined btn-primary" href="<?=$this->basePath()?>/panier/ajout/<?=$this->escapeHtml($product->_id)?>">Ajouter au panier</a>
            </div>
        </div>

    </div>




</div>
</main>
