<header>
</header>
<h3>Accueil</h3></br>
<main>
    <div class="in row">
        <div class="contenuPanier col-lg-12 col-md-12 col-sm-12 col-12 row" >
            <!-- Affiche chaque produit -->
            <?php foreach ($products as $p) : ?>
            <div class="col-lg-3 offset-lg-1 col-md-3  col-sm-3 col-3">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <a href="<?= $this->url()?>/../../produits/<?= $this->escapeHtml($p->_id)?>" class="produitDescTitre"><?= $this->escapeHtml($p->_name) ?></a>
                        <span class="prix_index"><?= $this->escapeHtml($p->_price) ?> $CAN</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <a href="<?= $this->url()?>/../../produits/<?= $this->escapeHtml($p->_id)?>"><img class="imageGrille" src="http://jhaegman.com/stool.svg"></a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-5 col-md-8 col-sm-8 col-8 voir_plus">
                        <a href="<?= $this->url()?>/../../produits/<?= $this->escapeHtml($p->_id)?>" class="btn btn-default btn-block ">Voir
                            plus</a>
                    </div>
                    <div class="col-lg-4 col-md-2 col-sm-2 col-1">
                        <a href="<?= $this->url()?>/../../panier/ajout/<?=$this->escapeHtml($p->_id)?>" class="ajout btn btn-outlined btn-primary"><span style="display:block">Ajouter</span></a>
                    </div>
                </div>
                <hr>
            </div>
            <?php endforeach; ?>
        </div>
    </div>

    <!-- Si la pagination est activée, affiche un menu de navigation -->
    <?php if ($products->count()): ?>

    <center>
    <div>
        <ul class="pagination">

        <?php
            $page=0;
            //Pour chaque page
            while($page!=$products->count()){
                $page++;
                //Page actuelle (classe "active")
                if($page==$products->getCurrentPageNumber()){
                    echo "<li class='active'><a>".$products->getCurrentPageNumber()."</a></li>";
                }
                //Autres pages
                else{
                    echo "<li><a href='".$this->url()."/../".$page."'>".$page.'</a></li>';
                }
            }
            ?>
        </ul>
    </div>
    </center>
    <?php endif; ?>
</main>