<header>
</header>

<main>
    <h3>Administration</h3></br>
    <style>form>input{margin:0 0 5px 0}</style>
    <div class="produitPanier row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-4">
            <form action="administration/ajout" method="post">
                <strong class="col-lg-12" style="font-size:2em;margin-bottom: 20px;"><span>Ajouter un produit</span></strong>
                <input class="col-lg-12" name="name" placeholder="Ex: Tabouret en fer"/>
                <input class="col-lg-12" name="description" placeholder="Ex: Très joli tabouret en fer"/>
                <input class="col-lg-4" name="price" placeholder="Ex: 50"/><strong>  $CAN</strong>
                <button class="col-lg-12 btn btn-outlined btn-primary" type="submit">Ajouter</button>
            </form>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 col-4">
            <form id="formEdition" action="administration/edition" method="post" class="hidden">
                <strong class="col-lg-12" style="font-size:2em;margin-bottom: 20px;"><span>Editer un produit</span></strong>
                <input id="formEditionId" name="id" type="hidden"/>
                <input class="col-lg-12" id="formEditionName" name="name" placeholder="Nom"/>
                <input class="col-lg-12" id="formEditionDescription" name="description" placeholder="Description"/>
                <input class="col-lg-4" id="formEditionPrice" name="price" placeholder="Prix"/>
                <button class="col-lg-12 btn btn-outlined btn-primary" type="submit">Editer un produit</button>
            </form>
        </div>
    </div>
    <br>
    <hr>
    <?php
        foreach ($products as $p) :


            echo '<div class="produitPanier row">';
            echo '<div class="col-lg-2 col-md-2 col-sm-2 col-2">';
            echo '<a href="'.$this->basePath().'/produits/'.$this->escapeHtml($p->_id).'"><img class="imageListe" src="http://jhaegman.com/stool.svg"></a>';

            echo '</div>';
            echo '<div class="col-lg-3 offset-lg-1 col-md-4 offset-md-2 col-sm-4 offset-sm-2 col-4 offset-3">';
            echo '<a href="'.$this->basePath().'/produits/'.$this->escapeHtml($p->_id).'">'.$this->escapeHtml($p->_name).'</a>';
            echo '<p class="produitDescParagraphe">'.$this->escapeHtml($p->_description).'</p>';
            echo '</div>';
            echo '<div class="col-lg-2 offset-lg-4 col-md-2 offset-md-1 col-sm-2 offset-sm-1 col-3">';
            echo '<span class="produitDescPrix">'.$this->escapeHtml($p->_price).'$CAN'.'</span><br></div>';

            echo '<div class="col-lg-1 offset-lg-3 col-md-2 offset-md-1 col-sm-2 offset-sm-1 col-3">';
            echo '<a href="#formEdition" onclick="fillEdit('.$this->escapeHtml($p->_id).',\''.$this->escapeHtml($p->_name).'\',\''.$this->escapeHtml($p->_description).'\','.$this->escapeHtml($p->_price).')">Editer</a><br></div>';

            echo '<div class="col-lg-2 offset-lg-2 col-md-2 offset-md-1 col-sm-2 offset-sm-1 col-3">';
            echo '<a href="'.$this->basePath().'/administration/suppression/'.$this->escapeHtml($p->_id).'">Supprimer des produits</a><br></div>';

            echo '<br><br></div><hr>';

        endforeach;

    ?>

</main>



<script>
    //Rempli le formulaire grace à la fonction appellée au clic sur l'édition
    function fillEdit(id,name,description,price){
        console.log("hey");
        document.getElementById("formEditionId").value =id;
        document.getElementById("formEditionName").value =name;
        document.getElementById("formEditionDescription").value =description;
        document.getElementById("formEditionPrice").value =price;

        document.getElementById("formEdition").classList.remove("hidden");
    }
</script>